# Generated by Django 5.0.3 on 2024-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hw_2_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_added",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
