# Generated by Django 5.0.3 on 2024-04-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hw_2_app", "0002_alter_order_date_ordered_alter_product_date_added_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="adress",
            new_name="address",
        ),
    ]
